//package database;
//
//import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
//import java.sql.Statement;
//
//public class HighScoreRepository {
//
//    public void initialize() {
//        if (!DatabaseConnection.isConfigured()) {
//            return;
//        }
//
//        String sql = """
//                CREATE TABLE snake_high_scores (
//                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//                    game_mode VARCHAR2(30) NOT NULL,
//                    score NUMBER NOT NULL,
//                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
//                )
//                """;
//
//        try (Connection connection = DatabaseConnection.getConnection();
//             Statement statement = connection.createStatement()) {
//            statement.execute(sql);
//        } catch (SQLException e) {
//            if (e.getErrorCode() != 955) {
//                System.err.println("Unable to initialize snake_high_scores table.");
//                e.printStackTrace();
//            }
//        }
//    }
//
//    public void saveSinglePlayerScore(int score) {
//        if (!DatabaseConnection.isConfigured()) {
//            return;
//        }
//
//        String sql = "INSERT INTO snake_high_scores (game_mode, score) VALUES (?, ?)";
//
//        try (Connection connection = DatabaseConnection.getConnection();
//             PreparedStatement statement = connection.prepareStatement(sql)) {
//            statement.setString(1, "SINGLE_PLAYER");
//            statement.setInt(2, score);
//            statement.executeUpdate();
//        } catch (SQLException e) {
//            System.err.println("Unable to save score to Oracle database.");
//            e.printStackTrace();
//        }
//    }
//
//    public int getBestSinglePlayerScore() {
//        if (!DatabaseConnection.isConfigured()) {
//            return 0;
//        }
//
//        String sql = "SELECT NVL(MAX(score), 0) AS best_score FROM snake_high_scores WHERE game_mode = ?";
//
//        try (Connection connection = DatabaseConnection.getConnection();
//             PreparedStatement statement = connection.prepareStatement(sql)) {
//            statement.setString(1, "SINGLE_PLAYER");
//
//            try (ResultSet resultSet = statement.executeQuery()) {
//                if (resultSet.next()) {
//                    return resultSet.getInt("best_score");
//                }
//            }
//        } catch (SQLException e) {
//            System.err.println("Unable to load high score from Oracle database.");
//            e.printStackTrace();
//        }
//
//        return 0;
//    }
//}
